apiVersion: v1
kind: Secret
metadata:
  name: translation-bot-secrets
  namespace: ${NAMESPACE}
type: Opaque
data:
  TOKEN: ${TOKEN_B64}
  MONGO_URI: ${MONGO_URI_B64}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL_B64}
  FEEDBACK_WEBHOOK: ${FEEDBACK_WEBHOOK_B64}
  TRANSLATE_WEBHOOK: ${TRANSLATE_WEBHOOK_B64}
  OPENAI_API_KEY: ${OPENAI_API_KEY_B64}
